require "lib.control_messages"
require "lib.go_registry"
require "lib.locales"

-- Screen Settings --
GAME_SCREEN_H = tonumber(sys.get_config("display.height"))
GAME_SCREEN_W = tonumber(sys.get_config("display.width"))
BOTTOM_MARGIN_HEIGTH = 0.1 * GAME_SCREEN_H
IMAGE_MARGIN = 0.3 * GAME_SCREEN_H


-- Layers Z Settings
Z_LAYER_BG = 0.6
Z_LAYER_GAME_OBJECTS = 0.7
Z_LAYER_TILE = 0.7
Z_LAYER_PLAYER = 0.8
Z_LAYER_LASER_BEAM = 0.75
Z_LAYER_TUTORIAL_HINTS = 0.95
Z_LAYER_FX = 0.85
Z_LAYER_GUI = 0.9

-- GUI Settings

SPRITE_WIDTH = 96
GUI_START_X = 96
AVATAR_X_OFFSET = 15
GUI_START_Y = GAME_SCREEN_H - 10 - SPRITE_WIDTH / 2

LEFT_TOP_CORNER_GUI_POS = vmath.vector3(GAME_SCREEN_W * 0.1, GAME_SCREEN_H * 0.9, Z_LAYER_GUI)

LEFT_LABEL_POS_X = GAME_SCREEN_W * 0.1
LEFT_LABEL_POS_Y = GAME_SCREEN_H * 0.5

TUTORIAL_Z_COORD = 0.98
LASER_Z_COORD = 0.97
DIRT_SPOT_Z_COORD = 0.955
CLEANABLE_OBJECT_Z_COORD = 0.94
CLEANABLE_OBJECT_GLOW_EFFECT_Z_COORD = 0.93

RIGTH_LABEL_POS_X = GAME_SCREEN_W * 0.87

LEFT_LABEL_POS = vmath.vector3(LEFT_LABEL_POS_X, LEFT_LABEL_POS_Y, 0.95)
RIGHT_LABEL_POS = vmath.vector3(RIGTH_LABEL_POS_X, LEFT_LABEL_POS_Y, 0.95)

LEFT_HIDDEN_LABEL_POS = vmath.vector3(LEFT_LABEL_POS_X, -50, 0.95)
RIGHT_HIDDEN_LABEL_POS = vmath.vector3(RIGTH_LABEL_POS_X, -50, 0.95)

WEST_HIDDEN_POS = vmath.vector3(-300, GAME_SCREEN_H / 2, 0.96)
EAST_HIDDEN_POS = vmath.vector3(GAME_SCREEN_W + 300, GAME_SCREEN_H / 2, 0.96)
CENTER_POS = vmath.vector3(GAME_SCREEN_W / 2, GAME_SCREEN_H  / 2, 0.96)

CENTER_HIDDEN_POS = vmath.vector3(GAME_SCREEN_W / 2, GAME_SCREEN_H + 300, 0.96)
NORTH_POS = vmath.vector3(GAME_SCREEN_W / 2, 0.9 * GAME_SCREEN_H, 0.96)
NORTH_LOWER_POS = vmath.vector3(GAME_SCREEN_W / 2, 0.8 * GAME_SCREEN_H, 0.96)

GUI_CENTER_POS = vmath.vector3(GAME_SCREEN_W / 2, GAME_SCREEN_H / 2, 0)
GUI_SOUTH_HIDDEN_POS = vmath.vector3(GAME_SCREEN_W / 2, -GAME_SCREEN_H * 1.5, 0)

EAST_POS = vmath.vector3(GAME_SCREEN_W * 0.2, GAME_SCREEN_H / 2, 0.96)
WEST_POS = vmath.vector3(GAME_SCREEN_W * 0.8, GAME_SCREEN_H / 2, 0.96)

RECORD_RIBBON_WEST_HIDDEN_POS = vmath.vector3(-GAME_SCREEN_W * 4, GAME_SCREEN_H * 0.84, 0.96)
RIBBON_NORTH_POS = vmath.vector3(GAME_SCREEN_W / 2, GAME_SCREEN_H * 0.8, 0.96)
RIBBON_HIDDEN_NORTH_POS = vmath.vector3(GAME_SCREEN_W / 2, GAME_SCREEN_H * 1.5, 0.96)
RIBBON_HIDDEN_SOUTH_POS = vmath.vector3(GAME_SCREEN_W / 2, -GAME_SCREEN_H * 0.25, 0.96)
RECORD_RIBBON_CENTER_POS = vmath.vector3(GAME_SCREEN_W / 2, GAME_SCREEN_H * 0.84, 0.96)
RECORD_RIBBON_BLINK_EAST_POS = vmath.vector3(GAME_SCREEN_W * 4, GAME_SCREEN_H * 0.84, 0.96)
RECORD_RIBBON_EAST_POS = vmath.vector3(GAME_SCREEN_W * 4, GAME_SCREEN_H * 0.84, 0.96)

-- Level Placement Settings
PLATFORM_PLACEMENT_Y = 220
GROUND_PLACEMENT_Y = 32

LEVEL_SEGMENT_X_OFFSET = GAME_SCREEN_W / 2
LEVEL_SEGMENT_X_RIGHT_MARGIN = 50


-- GAME Parameters

-- COLORS
COLOR_RED = vmath.vector4(1, 0, 0, 1)
COLOR_WHITE = vmath.vector4(1, 1, 1, 1)
COLOR_GREEN = vmath.vector4(0, 1, 0, 1)
COLOR_GRAY = vmath.vector4(0.1, 0.1, 0.1, 1)
COLOR_TRANSPARENT = vmath.vector4(1, 1, 1, 0)
COLOR_TRANSPARENT_RED_75_PERCENT = vmath.vector4(1, 0.1, 0.1, 0.75)
COLOR_TRANSPARENT_50_PERCENT = vmath.vector4(1, 1, 1, 0.5)
COLOR_TRANSPARENT_50_PERCENT_BLACKISH = vmath.vector4(0, 0, 0, 0.2)

COLOR_GREEN_PROGRESS_BAR_1 = vmath.vector4(99 / 255, 117 / 255, 94 / 255, 1)
COLOR_GREEN_PROGRESS_BAR_2 = vmath.vector4(27 / 255, 157 / 255, 0, 1)

COLOR_WHITE_255_FORMAT = vmath.vector4(255, 255, 255, 255)
COLOR_50_PERCENT_BLACKISH_255_FORMAT = vmath.vector4(255, 255, 255, 51)

TILE_CRUSHER_TILES_OFFSET_X = GAME_SCREEN_W * 0.4
PLAYER_POSITION = vmath.vector3(250, GAME_SCREEN_H / 2, Z_LAYER_PLAYER)
CAMERA_POSITION = vmath.vector3(250 + 380, GAME_SCREEN_H / 2, Z_LAYER_PLAYER)
LASER_BEAM_POSITION = vmath.vector3(PLAYER_POSITION.x, PLAYER_POSITION.y + 5, Z_LAYER_LASER_BEAM)

-- Special tile objects
TILE_DIRTY = 1