-- Put functions in this file to use them in several other scripts.
-- To get access to the functions, you need to put:
-- require "my_directory.my_file"
-- in any script using the functions.

APP_VERSION = '0.1.1'

TILES_Y_OFFSET = 60
TILE_CRUSHER_TILE_SIZE = 32
TILE_CRUSHER_TILE_TILE_HP = 14
TILE_CRUSHER_TILE_DAMAGE = 0.04
MONEY_INCREMENT = 6
--TILE_CRUSHER_TILE_DAMAGE = 0.25

--TILE_CRUSHER_ENERGY_DECREMENT_SIZE = 0.0032

--TILE_CRUSHER_ENERGY_DECREMENT_SIZE = 0.0001
--TILE_CRUSHER_ENERGY_DECREMENT_SIZE = 0.5
--TILE_CRUSHER_ENERGY_DECREMENT_SIZE = 0.1
TILE_CRUSHER_ENERGY_DECREMENT_SIZE = 0.0028
TILE_CRUSHER_MONEY_INCREMENT_SIZE = 4

CAMERA_MOVEMENT_TO_FIT_OBJECT_MODE_ENABLED = false

APP_NAME = 'powerwash_2d_yg'
DEBUG = false
DEBUG_LABEL_TEXT = "DEBUG_MODE_ACTIVATED"
--DEBUG_LABEL_TEXT = ""
DEBUG_LANGUAGE = "ru"
DEBUG_SHOW_DEBUG_INDICATOR = false
CALL_RESTART_GAME_DIALOG = true
CALL_RESTART_GAME_DIALOG_DELAY_SEC = 0.1
SHOW_RECORD_RIBBON = true

CONFIG_DESKTOP_VERSION = false

SOUND_ENABLED = true

RENDER_STEP = 0.08

print('App Version: ', APP_VERSION)
